# Generated by Django 4.0.3 on 2022-03-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['-brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=264)),
                ('preview_text', models.CharField(blank=True, max_length=75, null=True)),
                ('product_description', models.CharField(blank=True, max_length=1500, null=True)),
                ('product_image', models.ImageField(upload_to='products')),
                ('product_price', models.FloatField()),
                ('product_old_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('Product_stock', models.BooleanField(default=True)),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('Product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_brand', to='Shop.brand')),
            ],
            options={
                'ordering': ['-product_created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=80)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('category_created', models.DateTimeField(auto_now_add=True)),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_children', to='Shop.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-category_name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='Shop.category'),
        ),
    ]
