# Generated by Django 4.0.3 on 2022-03-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_product_brand_product_product_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_slug',
        ),
    ]
