# Generated by Django 4.0.3 on 2022-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_product_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
    ]
