# Generated by Django 4.0.3 on 2022-03-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_product_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
