# Generated by Django 4.0.3 on 2022-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_variationvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationvalue',
            name='price',
            field=models.IntegerField(default='50'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variationvalue',
            name='variation',
            field=models.CharField(choices=[('variant', 'variant'), ('color', 'color')], max_length=100),
        ),
    ]
