# Generated by Django 4.0.3 on 2022-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_rename_banner_active_banner_banner_active_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favicon',
            name='active_icon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logo',
            name='active_logo',
            field=models.BooleanField(default=False),
        ),
    ]
