# Generated by Django 4.0.3 on 2022-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_cart_color_cart_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttoorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'PayPal'), ('SSLcommerz', 'SSLcommerz')], default='Cash on Delivery', max_length=40),
        ),
    ]
